"""empty message

Revision ID: b3a18b3d53ed
Revises: 
Create Date: 2017-10-09 00:47:26.505854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a18b3d53ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pri_account_number', sa.String(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('alias', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('criticalities',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ordering')
    )
    op.create_table('dispositions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ordering')
    )
    op.create_table('hardware_types',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ordering')
    )
    op.create_table('materials',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('ordering')
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('references',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('by_id', sa.BigInteger(), nullable=False),
    sa.Column('by_class', sa.String(), nullable=False),
    sa.Column('to_id', sa.BigInteger(), nullable=False),
    sa.Column('to_class', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('roles', sa.String(), nullable=False),
    sa.Column('padawan', sa.Boolean(), nullable=True),
    sa.Column('supervisor_id', sa.BigInteger(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supervisor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workflow_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('advanced_searches',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('search_parameters', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmarked_id', sa.BigInteger(), nullable=False),
    sa.Column('bookmarked_class', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('change_log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['change_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discrepancies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discrepancy_number', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('disposition_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disposition_id'], ['dispositions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_table('links',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_specifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaid_settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('efab_user_id', sa.BigInteger(), nullable=False),
    sa.Column('mfab_user_id', sa.BigInteger(), nullable=False),
    sa.Column('plaid_admin_id', sa.BigInteger(), nullable=False),
    sa.Column('name_order', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['efab_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mfab_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plaid_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revision_log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('revisioned_by_id', sa.BigInteger(), nullable=False),
    sa.Column('revisioned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['revision_logs.id'], ),
    sa.ForeignKeyConstraint(['revisioned_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_by_id', sa.BigInteger(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('capacity', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('anomaly_type', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('criticality_id', sa.BigInteger(), nullable=False),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('corrective_action', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['criticality_id'], ['criticalities.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('design_number', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('export_control', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('revision_log_id', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_log_id'], ['revision_logs.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_number', 'revision', name='design_number_revision_unique')
    )
    op.create_table('ecos',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('analysis', sa.String(), nullable=True),
    sa.Column('corrective_action', sa.String(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('procedure_number', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('revision_log_id', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_log_id'], ['revision_logs.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('procedure_number', 'revision', name='procedure_number_revision_unique')
    )
    op.create_table('specifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('specification_number', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('revision_log_id', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revision_log_id'], ['revision_logs.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specification_number', 'revision', name='specification_number_revision_unique')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('assigned_to_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_by_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_on', sa.DateTime(), nullable=False),
    sa.Column('need_date', sa.DateTime(), nullable=False),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_parts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('part_number', sa.String(), nullable=False),
    sa.Column('current_best_estimate', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('predicted_best_estimate', sa.Float(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('material_specification_id', sa.BigInteger(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['material_specification_id'], ['material_specifications.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number', name='part_number_unique')
    )
    op.create_table('anomalies_approvers',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.PrimaryKeyConstraint('anomaly_id', 'approver_id')
    )
    op.create_table('anomalies_documents',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('anomaly_id', 'document_id')
    )
    op.create_table('anomalies_images',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('anomaly_id', 'image_id')
    )
    op.create_table('anomalies_links',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('anomaly_id', 'link_id')
    )
    op.create_table('as_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('as_run_number', sa.Integer(), nullable=False),
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('software_version', sa.String(), nullable=True),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designs_anomalies',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'anomaly_id')
    )
    op.create_table('designs_approvers',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'approver_id')
    )
    op.create_table('designs_documents',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'document_id')
    )
    op.create_table('designs_ecos',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('eco_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'eco_id')
    )
    op.create_table('designs_images',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'image_id')
    )
    op.create_table('designs_links',
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('design_id', 'link_id')
    )
    op.create_table('ecos_approvers',
    sa.Column('eco_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ),
    sa.PrimaryKeyConstraint('eco_id', 'approver_id')
    )
    op.create_table('ecos_documents',
    sa.Column('eco_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ),
    sa.PrimaryKeyConstraint('eco_id', 'document_id')
    )
    op.create_table('ecos_images',
    sa.Column('eco_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('eco_id', 'image_id')
    )
    op.create_table('ecos_links',
    sa.Column('eco_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['eco_id'], ['ecos.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('eco_id', 'link_id')
    )
    op.create_table('parts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('part_identifier', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('current_best_estimate', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=False),
    sa.Column('predicted_best_estimate', sa.Float(), nullable=False),
    sa.Column('design_id', sa.BigInteger(), nullable=False),
    sa.Column('material_id', sa.BigInteger(), nullable=True),
    sa.Column('material_specification_id', sa.BigInteger(), nullable=True),
    sa.Column('inseparable_component', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['material_specification_id'], ['material_specifications.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_identifier', 'design_id', name='part_identifier_design_unique')
    )
    op.create_table('procedures_approvers',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'approver_id')
    )
    op.create_table('procedures_documents',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'document_id')
    )
    op.create_table('procedures_images',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'image_id')
    )
    op.create_table('procedures_links',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'link_id')
    )
    op.create_table('procedures_vendor_parts',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'vendor_part_id')
    )
    op.create_table('specifications_approvers',
    sa.Column('specification_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('specification_id', 'approver_id')
    )
    op.create_table('specifications_documents',
    sa.Column('specification_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('specification_id', 'document_id')
    )
    op.create_table('specifications_images',
    sa.Column('specification_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('specification_id', 'image_id')
    )
    op.create_table('specifications_links',
    sa.Column('specification_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['specification_id'], ['specifications.id'], ),
    sa.PrimaryKeyConstraint('specification_id', 'link_id')
    )
    op.create_table('tasks_documents',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'document_id')
    )
    op.create_table('tasks_images',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'image_id')
    )
    op.create_table('tasks_links',
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'link_id')
    )
    op.create_table('vendor_builds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('build_identifier', sa.String(), nullable=False),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('purchase_order', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('manufacturer_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_identifier', 'vendor_part_id', name='build_identifier_vendor_part_unique')
    )
    op.create_table('vendor_parts_anomalies',
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('vendor_part_id', 'anomaly_id')
    )
    op.create_table('vendor_parts_approvers',
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('vendor_part_id', 'approver_id')
    )
    op.create_table('vendor_parts_documents',
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('vendor_part_id', 'document_id')
    )
    op.create_table('vendor_parts_images',
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('vendor_part_id', 'image_id')
    )
    op.create_table('vendor_parts_links',
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('vendor_part_id', 'link_id')
    )
    op.create_table('as_runs_anomalies',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomalies.id'], ),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'anomaly_id')
    )
    op.create_table('as_runs_approvers',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'approver_id')
    )
    op.create_table('as_runs_documents',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'document_id')
    )
    op.create_table('as_runs_images',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'image_id')
    )
    op.create_table('as_runs_links',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'link_id')
    )
    op.create_table('builds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('build_identifier', sa.String(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('purchase_order', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_identifier', 'part_id', name='build_identifier_part_unique')
    )
    op.create_table('part_components',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedures_parts',
    sa.Column('procedure_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.id'], ),
    sa.PrimaryKeyConstraint('procedure_id', 'part_id')
    )
    op.create_table('vendor_builds_discrepancies',
    sa.Column('vendor_build_id', sa.BigInteger(), nullable=False),
    sa.Column('discrepancy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.ForeignKeyConstraint(['vendor_build_id'], ['vendor_builds.id'], ),
    sa.PrimaryKeyConstraint('vendor_build_id', 'discrepancy_id')
    )
    op.create_table('vendor_builds_documents',
    sa.Column('vendor_build_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['vendor_build_id'], ['vendor_builds.id'], ),
    sa.PrimaryKeyConstraint('vendor_build_id', 'document_id')
    )
    op.create_table('vendor_products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('measured_mass', sa.Float(), nullable=True),
    sa.Column('hardware_type_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_build_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['hardware_types.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['vendor_build_id'], ['vendor_builds.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', 'vendor_part_id', name='serial_number_vendor_part_unique')
    )
    op.create_table('as_runs_vendor_products',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'vendor_product_id')
    )
    op.create_table('builds_discrepancies',
    sa.Column('build_id', sa.BigInteger(), nullable=False),
    sa.Column('discrepancy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'discrepancy_id')
    )
    op.create_table('builds_documents',
    sa.Column('build_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('build_id', 'document_id')
    )
    op.create_table('products',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('self_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(), nullable=True),
    sa.Column('measured_mass', sa.Float(), nullable=True),
    sa.Column('hardware_type_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('build_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('thumbnail_id', sa.BigInteger(), nullable=True),
    sa.Column('workflow_log_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_id', sa.BigInteger(), nullable=False),
    sa.Column('change_log_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ),
    sa.ForeignKeyConstraint(['change_log_id'], ['change_logs.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hardware_type_id'], ['hardware_types.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['workflow_log_id'], ['workflow_logs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number', 'part_id', name='serial_number_part_unique')
    )
    op.create_table('vendor_products_approvers',
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('vendor_product_id', 'approver_id')
    )
    op.create_table('vendor_products_discrepancies',
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.Column('discrepancy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('vendor_product_id', 'discrepancy_id')
    )
    op.create_table('vendor_products_documents',
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('vendor_product_id', 'document_id')
    )
    op.create_table('vendor_products_images',
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('vendor_product_id', 'image_id')
    )
    op.create_table('vendor_products_links',
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('vendor_product_id', 'link_id')
    )
    op.create_table('as_runs_products',
    sa.Column('as_run_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['as_run_id'], ['as_runs.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('as_run_id', 'product_id')
    )
    op.create_table('extra_product_components',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_components',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=False),
    sa.Column('part_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_part_id', sa.BigInteger(), nullable=True),
    sa.Column('vendor_product_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['vendor_part_id'], ['vendor_parts.id'], ),
    sa.ForeignKeyConstraint(['vendor_product_id'], ['vendor_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_approvers',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('approver_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'approver_id')
    )
    op.create_table('products_discrepancies',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('discrepancy_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['discrepancy_id'], ['discrepancies.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'discrepancy_id')
    )
    op.create_table('products_documents',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'document_id')
    )
    op.create_table('products_images',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'image_id')
    )
    op.create_table('products_links',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('link_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_links')
    op.drop_table('products_images')
    op.drop_table('products_documents')
    op.drop_table('products_discrepancies')
    op.drop_table('products_approvers')
    op.drop_table('product_components')
    op.drop_table('extra_product_components')
    op.drop_table('as_runs_products')
    op.drop_table('vendor_products_links')
    op.drop_table('vendor_products_images')
    op.drop_table('vendor_products_documents')
    op.drop_table('vendor_products_discrepancies')
    op.drop_table('vendor_products_approvers')
    op.drop_table('products')
    op.drop_table('builds_documents')
    op.drop_table('builds_discrepancies')
    op.drop_table('as_runs_vendor_products')
    op.drop_table('vendor_products')
    op.drop_table('vendor_builds_documents')
    op.drop_table('vendor_builds_discrepancies')
    op.drop_table('procedures_parts')
    op.drop_table('part_components')
    op.drop_table('builds')
    op.drop_table('as_runs_links')
    op.drop_table('as_runs_images')
    op.drop_table('as_runs_documents')
    op.drop_table('as_runs_approvers')
    op.drop_table('as_runs_anomalies')
    op.drop_table('vendor_parts_links')
    op.drop_table('vendor_parts_images')
    op.drop_table('vendor_parts_documents')
    op.drop_table('vendor_parts_approvers')
    op.drop_table('vendor_parts_anomalies')
    op.drop_table('vendor_builds')
    op.drop_table('tasks_links')
    op.drop_table('tasks_images')
    op.drop_table('tasks_documents')
    op.drop_table('specifications_links')
    op.drop_table('specifications_images')
    op.drop_table('specifications_documents')
    op.drop_table('specifications_approvers')
    op.drop_table('procedures_vendor_parts')
    op.drop_table('procedures_links')
    op.drop_table('procedures_images')
    op.drop_table('procedures_documents')
    op.drop_table('procedures_approvers')
    op.drop_table('parts')
    op.drop_table('ecos_links')
    op.drop_table('ecos_images')
    op.drop_table('ecos_documents')
    op.drop_table('ecos_approvers')
    op.drop_table('designs_links')
    op.drop_table('designs_images')
    op.drop_table('designs_ecos')
    op.drop_table('designs_documents')
    op.drop_table('designs_approvers')
    op.drop_table('designs_anomalies')
    op.drop_table('as_runs')
    op.drop_table('anomalies_links')
    op.drop_table('anomalies_images')
    op.drop_table('anomalies_documents')
    op.drop_table('anomalies_approvers')
    op.drop_table('vendor_parts')
    op.drop_table('tasks')
    op.drop_table('specifications')
    op.drop_table('procedures')
    op.drop_table('ecos')
    op.drop_table('designs')
    op.drop_table('anomalies')
    op.drop_table('workflow_log_entries')
    op.drop_table('revision_log_entries')
    op.drop_table('plaid_settings')
    op.drop_table('material_specifications')
    op.drop_table('links')
    op.drop_table('images')
    op.drop_table('documents')
    op.drop_table('discrepancies')
    op.drop_table('change_log_entries')
    op.drop_table('bookmarks')
    op.drop_table('approvers')
    op.drop_table('advanced_searches')
    op.drop_table('workflow_logs')
    op.drop_table('users')
    op.drop_table('revision_logs')
    op.drop_table('references')
    op.drop_table('projects')
    op.drop_table('materials')
    op.drop_table('hardware_types')
    op.drop_table('dispositions')
    op.drop_table('criticalities')
    op.drop_table('companies')
    op.drop_table('change_logs')
    # ### end Alembic commands ###
