version: '2'

services:

  nginx:
    image: nginx:latest
    hostname: plaid_nginx
    container_name: nginx
    restart: "no"
    depends_on:
      - plaid
    ports:
      - "5000:5000"
    volumes:
      - ./conf/nginx:/etc/nginx/conf.d
      - ./logs:/var/log/nginx

  rabbitmq:
    image: rabbitmq:3.6.10
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=plaid_rabbit
      - RABBITMQ_DEFAULT_PASS=YOUR_RABBIT_PASS_HERE
      - RABBITMQ_DEFAULT_VHOST=plaid_amqp
      - RABBITMQ_ERLANG_COOKIE=YOUR_RABBIT_COOKIE_HERE
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbitmq/rabbitmq.log
      - RABBITMQ_SASL_LOGS=/var/log/rabbitmq/rabbitmq/rabbitmq_sasl.log
      - RABBITMQ_HIPE_COMPILE=1
    volumes:
      - ./logs:/var/log/rabbitmq
    ports:
      - "5672:5672"

  plaid:
    build: .
    container_name: plaid
    restart: always
    depends_on:
      - rabbitmq
    environment:
      - PLAID_LOG_FILE=/var/log/plaid/plaid/plaid.log
    volumes:
      - ./logs:/var/log/plaid
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
